// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: server/grpc/proto/blog/blog.proto

package blog

import (
	user "github.com/hariharasudhan-nineleaps/go-grpc-blogger/server/grpc/proto/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogCategory int32

const (
	BlogCategory_TECH          BlogCategory = 0
	BlogCategory_ENTERTAINMENT BlogCategory = 1
	BlogCategory_FASHION       BlogCategory = 2
	BlogCategory_EDUCATION     BlogCategory = 3
	BlogCategory_SPORTS        BlogCategory = 4
)

// Enum value maps for BlogCategory.
var (
	BlogCategory_name = map[int32]string{
		0: "TECH",
		1: "ENTERTAINMENT",
		2: "FASHION",
		3: "EDUCATION",
		4: "SPORTS",
	}
	BlogCategory_value = map[string]int32{
		"TECH":          0,
		"ENTERTAINMENT": 1,
		"FASHION":       2,
		"EDUCATION":     3,
		"SPORTS":        4,
	}
)

func (x BlogCategory) Enum() *BlogCategory {
	p := new(BlogCategory)
	*p = x
	return p
}

func (x BlogCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlogCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_server_grpc_proto_blog_blog_proto_enumTypes[0].Descriptor()
}

func (BlogCategory) Type() protoreflect.EnumType {
	return &file_server_grpc_proto_blog_blog_proto_enumTypes[0]
}

func (x BlogCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlogCategory.Descriptor instead.
func (BlogCategory) EnumDescriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{0}
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    BlogCategory `protobuf:"varint,4,opt,name=category,proto3,enum=blog.BlogCategory" json:"category,omitempty"`
	Tags        []string     `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBlogRequest) GetCategory() BlogCategory {
	if x != nil {
		return x.Category
	}
	return BlogCategory_TECH
}

func (x *CreateBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    BlogCategory `protobuf:"varint,4,opt,name=category,proto3,enum=blog.BlogCategory" json:"category,omitempty"`
	Tags        []string     `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Author      *user.User   `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBlogResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBlogResponse) GetCategory() BlogCategory {
	if x != nil {
		return x.Category
	}
	return BlogCategory_TECH
}

func (x *CreateBlogResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateBlogResponse) GetAuthor() *user.User {
	if x != nil {
		return x.Author
	}
	return nil
}

type UserBlog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    BlogCategory           `protobuf:"varint,4,opt,name=category,proto3,enum=blog.BlogCategory" json:"category,omitempty"`
	Tags        []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *UserBlog) Reset() {
	*x = UserBlog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBlog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlog) ProtoMessage() {}

func (x *UserBlog) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlog.ProtoReflect.Descriptor instead.
func (*UserBlog) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{2}
}

func (x *UserBlog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserBlog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserBlog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserBlog) GetCategory() BlogCategory {
	if x != nil {
		return x.Category
	}
	return BlogCategory_TECH
}

func (x *UserBlog) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UserBlog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserBlogResponseMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Prev  *string `protobuf:"bytes,2,opt,name=prev,proto3,oneof" json:"prev,omitempty"`
	Next  *string `protobuf:"bytes,3,opt,name=next,proto3,oneof" json:"next,omitempty"`
}

func (x *UserBlogResponseMetadata) Reset() {
	*x = UserBlogResponseMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBlogResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlogResponseMetadata) ProtoMessage() {}

func (x *UserBlogResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlogResponseMetadata.ProtoReflect.Descriptor instead.
func (*UserBlogResponseMetadata) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{3}
}

func (x *UserBlogResponseMetadata) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserBlogResponseMetadata) GetPrev() string {
	if x != nil && x.Prev != nil {
		return *x.Prev
	}
	return ""
}

func (x *UserBlogResponseMetadata) GetNext() string {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return ""
}

type UserBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  *uint32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset *string `protobuf:"bytes,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *UserBlogRequest) Reset() {
	*x = UserBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlogRequest) ProtoMessage() {}

func (x *UserBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlogRequest.ProtoReflect.Descriptor instead.
func (*UserBlogRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{4}
}

func (x *UserBlogRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *UserBlogRequest) GetOffset() string {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return ""
}

type UserBlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *UserBlogResponseMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Blogs    []*UserBlog               `protobuf:"bytes,2,rep,name=blogs,proto3" json:"blogs,omitempty"`
}

func (x *UserBlogResponse) Reset() {
	*x = UserBlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlogResponse) ProtoMessage() {}

func (x *UserBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlogResponse.ProtoReflect.Descriptor instead.
func (*UserBlogResponse) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{5}
}

func (x *UserBlogResponse) GetMetadata() *UserBlogResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserBlogResponse) GetBlogs() []*UserBlog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetUserBlogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlogId string `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
}

func (x *GetUserBlogRequest) Reset() {
	*x = GetUserBlogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBlogRequest) ProtoMessage() {}

func (x *GetUserBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpc_proto_blog_blog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBlogRequest.ProtoReflect.Descriptor instead.
func (*GetUserBlogRequest) Descriptor() ([]byte, []int) {
	return file_server_grpc_proto_blog_blog_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

var File_server_grpc_proto_blog_blog_proto protoreflect.FileDescriptor

var file_server_grpc_proto_blog_blog_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6c, 0x6f, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22,
	0xc4, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0xd1, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x74, 0x0a, 0x18, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x17, 0x0a, 0x04,
	0x70, 0x72, 0x65, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x72,
	0x65, 0x76, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x65, 0x78, 0x74,
	0x22, 0x5e, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x22, 0x74, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x2a, 0x53, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x67, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x43, 0x48, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x54, 0x41, 0x49, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x53, 0x48, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0d,
	0x0a, 0x09, 0x45, 0x44, 0x55, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x53, 0x10, 0x04, 0x32, 0xcc, 0x01, 0x0a, 0x0b, 0x42, 0x6c,
	0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x17, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x15, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x18, 0x2e, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x6c, 0x6f, 0x67, 0x22, 0x00, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x72, 0x69, 0x68, 0x61, 0x72, 0x61, 0x73,
	0x75, 0x64, 0x68, 0x61, 0x6e, 0x2d, 0x6e, 0x69, 0x6e, 0x65, 0x6c, 0x65, 0x61, 0x70, 0x73, 0x2f,
	0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x62, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_grpc_proto_blog_blog_proto_rawDescOnce sync.Once
	file_server_grpc_proto_blog_blog_proto_rawDescData = file_server_grpc_proto_blog_blog_proto_rawDesc
)

func file_server_grpc_proto_blog_blog_proto_rawDescGZIP() []byte {
	file_server_grpc_proto_blog_blog_proto_rawDescOnce.Do(func() {
		file_server_grpc_proto_blog_blog_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_grpc_proto_blog_blog_proto_rawDescData)
	})
	return file_server_grpc_proto_blog_blog_proto_rawDescData
}

var file_server_grpc_proto_blog_blog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_grpc_proto_blog_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_grpc_proto_blog_blog_proto_goTypes = []interface{}{
	(BlogCategory)(0),                // 0: blog.BlogCategory
	(*CreateBlogRequest)(nil),        // 1: blog.CreateBlogRequest
	(*CreateBlogResponse)(nil),       // 2: blog.CreateBlogResponse
	(*UserBlog)(nil),                 // 3: blog.UserBlog
	(*UserBlogResponseMetadata)(nil), // 4: blog.UserBlogResponseMetadata
	(*UserBlogRequest)(nil),          // 5: blog.UserBlogRequest
	(*UserBlogResponse)(nil),         // 6: blog.UserBlogResponse
	(*GetUserBlogRequest)(nil),       // 7: blog.GetUserBlogRequest
	(*user.User)(nil),                // 8: user.User
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_server_grpc_proto_blog_blog_proto_depIdxs = []int32{
	0,  // 0: blog.CreateBlogRequest.category:type_name -> blog.BlogCategory
	0,  // 1: blog.CreateBlogResponse.category:type_name -> blog.BlogCategory
	8,  // 2: blog.CreateBlogResponse.author:type_name -> user.User
	0,  // 3: blog.UserBlog.category:type_name -> blog.BlogCategory
	9,  // 4: blog.UserBlog.created_at:type_name -> google.protobuf.Timestamp
	4,  // 5: blog.UserBlogResponse.metadata:type_name -> blog.UserBlogResponseMetadata
	3,  // 6: blog.UserBlogResponse.blogs:type_name -> blog.UserBlog
	1,  // 7: blog.BlogService.CreateBlog:input_type -> blog.CreateBlogRequest
	5,  // 8: blog.BlogService.GetUserBlogs:input_type -> blog.UserBlogRequest
	7,  // 9: blog.BlogService.GetUserBlog:input_type -> blog.GetUserBlogRequest
	2,  // 10: blog.BlogService.CreateBlog:output_type -> blog.CreateBlogResponse
	6,  // 11: blog.BlogService.GetUserBlogs:output_type -> blog.UserBlogResponse
	3,  // 12: blog.BlogService.GetUserBlog:output_type -> blog.UserBlog
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_grpc_proto_blog_blog_proto_init() }
func file_server_grpc_proto_blog_blog_proto_init() {
	if File_server_grpc_proto_blog_blog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_grpc_proto_blog_blog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBlog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBlogResponseMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_grpc_proto_blog_blog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBlogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_server_grpc_proto_blog_blog_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_server_grpc_proto_blog_blog_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_grpc_proto_blog_blog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpc_proto_blog_blog_proto_goTypes,
		DependencyIndexes: file_server_grpc_proto_blog_blog_proto_depIdxs,
		EnumInfos:         file_server_grpc_proto_blog_blog_proto_enumTypes,
		MessageInfos:      file_server_grpc_proto_blog_blog_proto_msgTypes,
	}.Build()
	File_server_grpc_proto_blog_blog_proto = out.File
	file_server_grpc_proto_blog_blog_proto_rawDesc = nil
	file_server_grpc_proto_blog_blog_proto_goTypes = nil
	file_server_grpc_proto_blog_blog_proto_depIdxs = nil
}
